default_context:
  package_name: sunkit-dem
  module_name: sunkit_dem
  short_description: A package for computing solar differential emission measure distributions
  author_name: SunPy Developers
  author_email:
  license: BSD 3-Clause
  project_url: https://github.com/sunpy/sunkit-dem
  github_repo: sunpy/sunkit-dem
  minimum_python_version: 3.7
  use_compiled_extensions: n
  include_example_code: n
